sudo: false
language: python
python:
- 3.3
- 3.4
- 3.5
- nightly
cache: pip
install:
- pip install -r requirements.txt
script:
- python3 setup.py test --pytest-args='--cov=pypcappy'
after_success:
- coveralls
before_deploy:
- python3 setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: sojyaKcRNP5ULqOFQ7rJHONkBVwJQieWmNNwyrckHDw3tFi5FGjoDmbXHDNu4FiAq28Rby/foqRfs42VYRXq3XVkDVNiEEpmXnVX+vHCJu9AnZG3HRJO7e46dkerZCBvSMbCOIfuCLexlD0mjmxoM9tfupFeOKFS299qjYJG2xx9z7h5EIurMmiEXMi5XU/YJ6pABC41olzmDymxlI3FDY83v3iYA9VRwRSrRKQQF/1gbZoeNMP3RbdfLLvZxe4SCraBBh0LX6paDvn6Wam2UzmnnRvP8vqc5xoEOKyUpaehTTnzIFh0TNxzIO5WFvZmJ89050e4pqGgu1mdiQCMeM6CX+HeEH0+y4a8m0UohE2ksOIxOQrZgp7u0QSFDpy6x5lw0q3qZoZiaDEDeZT5JYmttBiB6YznN2DWTvhfaSF5YnYWJZaJYlVPOWqHx60tfPxD9lqkNwIZFAYbDe1WjvxlUxjf9E9w2Vl4VQ26zeP15ov0Z4CMNskh9GsCwMLX5dpveHXvHBodHDSX8Mgbaiuc8TKj+tXZhv744vBtDzTAtBKss/skTMKlH8ePOrugQmdJdiZtNNR816MRAaZnITo7guq50lQn3hLEzhXHYaXt6BKhpVRFCjk7AjhERoQqGC6mbRpwVV5a1Ueoz8ES8DDIFX+SSjMW73MRjfIUUl4=
  file_glob: true
  file: dist/pypcappy-*.tar.gz
  skip_cleanup: true
  on:
    repo: TheBiggerGuy/pypcappy
    tags: true
    branch: master
