sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - "nightly"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python3 setup.py test --pytest-args='--cov=pypcappy'
after_success:
  - coveralls